using PureCloud.Client.Models;
using PureCloud.Client.Models.Conversations;
using PureCloud.Client.Models.Topics;
using PureCloud.Client.Models.Users;

namespace PureCloud.Client;

public static class PureCloudConstants
{
    public const string PureCloudAuthClientName = "PureCloudAuth";

    public const string PureCloudClientName = "PureCloud";

    public readonly static IReadOnlyDictionary<string, Type> TopicTemplates = new Dictionary<string, Type>()
    {
        {"v2.analytics.conversation.{0}.metrics", typeof(ConversationMetricsTopicConversationMetricRecord)},
        {"v2.analytics.conversations.details.jobs.availability", typeof(ConversationDetailsDatalakeAvailabilityTopicDataAvailabilityChangeNotification)},
        {"v2.analytics.flow.{0}.aggregates", typeof(StatEventFlowTopicStatsNotification)},
        {"v2.analytics.flow.{0}.metrics", typeof(FlowMetricsTopicFlowMetricRecord)},
        {"v2.analytics.flowoutcome.{0}.aggregates", typeof(StatEventFlowOutcomeTopicStatsNotification)},
        {"v2.analytics.queues.{0}.observations", typeof(StatEventQueueTopicStatsNotification)},
        {"v2.analytics.users.details.jobs.availability", typeof(UserDetailsDatalakeAvailabilityTopicDataAvailabilityChangeNotification)},
        {"v2.analytics.users.{0}.aggregates", typeof(StatEventUserTopicStatsNotification)},
        {"v2.analytics.wrapup.{0}.aggregates", typeof(StatEventWrapUpCodeTopicStatsNotification)},
        {"v2.architect.dependencytracking.build", typeof(ArchitectDependencyTrackingBuildNotificationDependencyTrackingBuildNotification)},
        {"v2.architect.prompts.{0}", typeof(ArchitectPromptNotificationPromptNotification)},
        {"v2.architect.prompts.{0}.resources.{1}", typeof(ArchitectPromptResourceNotificationPromptResourceNotification)},
        {"v2.architect.systemprompts.{0}.resources.{1}", typeof(ArchitectSystemPromptResourceNotificationSystemPromptResourceNotification)},
        {"v2.audits.entitytype.{0}.entityid.{1}", typeof(AuditTopicAuditLogMessage)},
        {"v2.bot.conversation.{0}.conversations.summaries", typeof(ConversationSummaryTopicVirtualAgentsConversationSummaryEvent)},
        {"v2.businessunits.{0}.workforcemanagement.intraday", typeof(WfmBuIntradayDataUpdateTopicBuIntradayNotification)},
        {"v2.contentmanagement.documents.{0}", typeof(ContentManagementSingleDocumentTopicDocumentDataV2)},
        {"v2.contentmanagement.workspaces.{0}.documents", typeof(ContentManagementWorkspaceDocumentsTopicDocumentDataV2)},
        {"v2.conversations.{0}.transcription", typeof(TranscriptionTopicTranscriptionMessage)},
        {"v2.detail.events.collaboratechat.adhoc.{0}.messages", typeof(CollaborateChatAdhocMessageEventTopicCollaborateChatMessage)},
        {"v2.detail.events.collaboratechat.group.{0}.messages", typeof(CollaborateChatGroupMessageEventTopicCollaborateChatMessage)},
        {"v2.detail.events.conversation.{0}.acd.end", typeof(AcdEndDetailEventTopicAcdEndEvent)},
        {"v2.detail.events.conversation.{0}.acd.start", typeof(AcdStartDetailEventTopicAcdStartEvent)},
        {"v2.detail.events.conversation.{0}.acw", typeof(AcwDetailEventTopicAfterCallWorkEvent)},
        {"v2.detail.events.conversation.{0}.attributes", typeof(AttributeDetailEventTopicAttributeUpdateEvent)},
        {"v2.detail.events.conversation.{0}.contact", typeof(ContactDetailEventTopicContactUpdateEvent)},
        {"v2.detail.events.conversation.{0}.customer.end", typeof(CustomerEndDetailEventTopicCustomerEndEvent)},
        {"v2.detail.events.conversation.{0}.customer.start", typeof(CustomerStartDetailEventTopicCustomerStartEvent)},
        {"v2.detail.events.conversation.{0}.flow.end", typeof(FlowEndDetailEventTopicFlowEndEvent)},
        {"v2.detail.events.conversation.{0}.flow.outcome", typeof(FlowOutcomeDetailEventTopicFlowOutcomeEvent)},
        {"v2.detail.events.conversation.{0}.flow.start", typeof(FlowStartDetailEventTopicFlowStartEvent)},
        {"v2.detail.events.conversation.{0}.outbound", typeof(OutboundDetailEventTopicOutboundInitEvent)},
        {"v2.detail.events.conversation.{0}.user.end", typeof(UserEndDetailEventTopicUserEndEvent)},
        {"v2.detail.events.conversation.{0}.user.start", typeof(UserStartDetailEventTopicUserStartEvent)},
        {"v2.detail.events.conversation.{0}.voicemail.end", typeof(VoicemailEndDetailEventTopicVoicemailEndEvent)},
        {"v2.detail.events.conversation.{0}.voicemail.start", typeof(VoicemailStartDetailEventTopicVoicemailStartEvent)},
        {"v2.detail.events.conversation.{0}.wrapup", typeof(WrapupDetailEventTopicWrapupEvent)},
        {"v2.employeeperformance.externalmetrics.definitions", typeof(EmployeePerformanceExternalMetricsDefinitionExternalMetricsDefinition)},
        {"v2.externalcontacts.contacts.{0}", typeof(ExternalContactsContactChangedTopicContact)},
        {"v2.externalcontacts.contacts.{0}.journey.sessions", typeof(JourneySessionEventsNotificationSessionEvent)},
        {"v2.externalcontacts.contacts.{0}.notes.{1}", typeof(ExternalContactsContactNoteChangedTopicNote)},
        {"v2.externalcontacts.contacts.{0}.unresolved", typeof(ExternalContactsUnresolvedContactChangedTopicContact)},
        {"v2.externalcontacts.organizations.{0}", typeof(ExternalContactsOrganizationChangedTopicExternalOrganization)},
        {"v2.externalcontacts.organizations.{0}.notes.{1}", typeof(ExternalContactsOrganizationNoteChangedTopicNote)},
        {"v2.externalcontacts.relationships.{0}", typeof(ExternalContactsRelationshipChangedTopicRelationship)},
        {"v2.flows.instances.flow.{0}", typeof(V2FlowExecutionDataFlowidTopicFlowExecutionHistory)},
        {"v2.flows.outcomes.{0}", typeof(ArchitectFlowOutcomeNotificationFlowOutcomeNotification)},
        {"v2.flows.{0}", typeof(ArchitectFlowNotificationFlowNotification)},
        {"v2.gamification.scorecards.users.{0}", typeof(GamificationScorecardChangeTopicScorecardChange)},
        {"v2.groups.{0}.greetings", typeof(GroupGreetingEventGreeting)},
        {"v2.journey.sessions.{0}.action.events", typeof(JourneyWebActionEventsNotificationWebActionEventsNotification)},
        {"v2.journey.sessions.{0}.app.events", typeof(JourneyAppEventsNotificationAppEventsNotification)},
        {"v2.journey.sessions.{0}.outcome.events", typeof(JourneyOutcomeEventsNotificationOutcomeEventsNotification)},
        {"v2.journey.sessions.{0}.web.events", typeof(JourneyWebEventsNotificationWebEventsNotification)},
        {"v2.managementunits.{0}.workforcemanagement.intraday", typeof(WfmIntradayDataUpdateTopicIntradayDataUpdate)},
        {"v2.operations.events.{0}", typeof(OperationalEventNotificationTopicOperationalEventNotification)},
        {"v2.outbound.attemptlimits.{0}", typeof(DialerAttemptLimitsConfigChangeAttemptLimits)},
        {"v2.outbound.callabletimesets.{0}", typeof(DialerCallabletimesetConfigChangeCallableTimeSet)},
        {"v2.outbound.campaignrules.{0}", typeof(DialerCampaignRuleConfigChangeCampaignRule)},
        {"v2.outbound.campaigns.{0}", typeof(DialerCampaignConfigChangeCampaign)},
        {"v2.outbound.campaigns.{0}.progress", typeof(DialerCampaignProgressEventCampaignProgress)},
        {"v2.outbound.campaigns.{0}.stats", typeof(StatEventCampaignTopicStatsNotification)},
        {"v2.outbound.contactlistfilters.{0}", typeof(DialerContactlistfilterConfigChangeContactListFilter)},
        {"v2.outbound.contactlists.{0}", typeof(DialerContactlistConfigChangeContactList)},
        {"v2.outbound.contactlists.{0}.importstatus", typeof(ContactlistImportStatusImportStatus)},
        {"v2.outbound.dnclists.{0}", typeof(DialerDnclistConfigChangeDncList)},
        {"v2.outbound.dnclists.{0}.importstatus", typeof(DnclistImportStatusImportStatus)},
        {"v2.outbound.email.campaigns.contact.postContact", typeof(OutboundMessagingCampaignPostContactEmailEventTopicOutboundMessagingCampaignPostContactEmailEvent)},
        {"v2.outbound.email.campaigns.contact.preContact", typeof(OutboundMessagingCampaignPreContactEmailEventTopicOutboundMessagingCampaignPreContactEmailEvent)},
        {"v2.outbound.emailcampaigns.{0}", typeof(OutboundMessagingEmailCampaignConfigChangeMessagingCampaign)},
        {"v2.outbound.emailcampaigns.{0}.progress", typeof(OutboundMessagingEmailCampaignProgressEventCampaignProgress)},
        {"v2.outbound.importtemplates.{0}.importstatus", typeof(ImportTemplateImportStatusImportStatus)},
        {"v2.outbound.messaging.campaigns.contact.postContact", typeof(OutboundMessagingCampaignPostContactSmsEventTopicOutboundMessagingCampaignPostContactSMSEvent)},
        {"v2.outbound.messaging.campaigns.contact.preContact", typeof(OutboundMessagingCampaignPreContactSmsEventTopicOutboundMessagingCampaignPreContactSMSEvent)},
        {"v2.outbound.messagingcampaigns.{0}", typeof(OutboundMessagingMessagingCampaignConfigChangeMessagingCampaign)},
        {"v2.outbound.messagingcampaigns.{0}.progress", typeof(OutboundMessagingMessagingCampaignProgressEventCampaignProgress)},
        {"v2.outbound.responsesets.{0}", typeof(DialerResponsesetConfigChangeResponseSet)},
        {"v2.outbound.rulesets.{0}", typeof(DialerRulesetConfigChangeRuleSet)},
        {"v2.outbound.schedules.campaigns.{0}", typeof(DialerCampaignScheduleConfigChangeCampaignSchedule)},
        {"v2.outbound.schedules.sequences.{0}", typeof(DialerSequenceScheduleConfigChangeSequenceSchedule)},
        {"v2.outbound.sequences.{0}", typeof(DialerSequenceConfigChangeCampaignSequence)},
        {"v2.outbound.settings", typeof(DialerOutboundSettingsConfigChangeOutboundSettings)},
        {"v2.outbound.whatsappcampaigns.{0}", typeof(OutboundMessagingWhatsappCampaignConfigChangeMessagingCampaign)},
        {"v2.outbound.whatsappcampaigns.{0}.progress", typeof(OutboundMessagingWhatsappCampaignProgressEventCampaignProgress)},
        {"v2.outbound.wrapupcodemappings.{0}", typeof(DialerWrapupcodemappingConfigChangeWrapUpCodeMapping)},
        {"v2.quality.evaluations", typeof(EvaluationQualityV2TopicEvaluationV2)},
        {"v2.routing.queues.{0}.conversations", typeof(QueueConversationEventTopicConversation)},
        {"v2.routing.queues.{0}.conversations.callbacks", typeof(QueueConversationCallbackEventTopicCallbackConversation)},
        {"v2.routing.queues.{0}.conversations.calls", typeof(QueueConversationCallEventTopicCallConversation)},
        {"v2.routing.queues.{0}.conversations.chats", typeof(QueueConversationChatEventTopicChatConversation)},
        {"v2.routing.queues.{0}.conversations.cobrowseSessions", typeof(QueueConversationCobrowseEventTopicCobrowseConversation)},
        {"v2.routing.queues.{0}.conversations.emails", typeof(QueueConversationEmailEventTopicEmailConversation)},
        {"v2.routing.queues.{0}.conversations.messages", typeof(QueueConversationMessageEventTopicMessageConversation)},
        {"v2.routing.queues.{0}.conversations.screenshares", typeof(QueueConversationScreenShareEventTopicScreenShareConversation)},
        {"v2.routing.queues.{0}.conversations.socialexpressions", typeof(QueueConversationSocialExpressionEventTopicConversation)},
        {"v2.routing.queues.{0}.conversations.videos", typeof(QueueConversationVideoEventTopicConversation)},
        {"v2.routing.queues.{0}.users", typeof(QueueUserEventTopicQueueMember)},
        {"v2.speechandtextanalytics.programs.general.jobs.{0}", typeof(CreateGeneralProgramTopicsDefinitionsJob)},
        {"v2.speechandtextanalytics.programs.publishjobs.{0}", typeof(PublishProgramTopicsDefinitionsJob)},
        {"v2.speechandtextanalytics.programs.topiclinks.jobs.{0}", typeof(ProgramTopicLinksTopicsDefinitionsJob)},
        {"v2.speechandtextanalytics.topics.publishjobs.{0}", typeof(PublishTopicTopicsDefinitionsJob)},
        {"v2.system.no_longer_subscribed.{0}", typeof(SystemMessage)},
        {"v2.system.socket_closing", typeof(SystemMessage)},
        {"v2.system.token_revoked.{0}", typeof(SystemMessage)},
        {"v2.system.{0}.{1}", typeof(SystemMessage)},
        {"v2.taskmanagement.workitems.queues.{0}", typeof(WorkitemsQueueEventsNotificationWorkitem)},
        {"v2.taskmanagement.workitems.users.{0}", typeof(WorkitemsUserEventsNotificationWorkitem)},
        {"v2.taskmanagement.workitems.{0}", typeof(WorkitemsEventsNotificationWorkitem)},
        // {"v2.telephony.providers.edges.phones.{0}", typeof(PhoneChangeTopicPhone)},
        // {"v2.telephony.providers.edges.trunks.{0}", typeof(TrunkInstanceTopicTrunk)},
        // {"v2.telephony.providers.edges.trunks.{0}.metrics", typeof(TrunkMetricsTopicTrunkMetrics)},
        // {"v2.telephony.providers.edges.{0}", typeof(EdgeChangeTopicEdge)},
        // {"v2.telephony.providers.edges.{0}.logicalinterfaces", typeof(EdgeLogicalInterfacesChangeTopicDomainLogicalInterfaceChange)},
        // {"v2.telephony.providers.edges.{0}.metrics", typeof(EdgeMetricsTopicEdgeMetrics)},
        // {"v2.telephony.providers.edges.{0}.softwareupdate", typeof(EdgeSoftwareUpdateTopicDomainEdgeSoftwareUpdate)},
        // {"v2.users.{0}.activity", typeof(AgentActivityChangedTopicAgentActivity)},
        // {"v2.users.{0}.alerting.alerts", typeof(V2MobiusAlertsTopicAlert)},
        // {"v2.users.{0}.alerting.heartbeat.alerts", typeof(KlaxonHeartBeatAlertsTopicHeartBeatAlert)},
        // {"v2.users.{0}.alerting.heartbeat.rules", typeof(KlaxonHeartBeatRulesTopicHeartBeatRule)},
        // {"v2.users.{0}.alerting.interactionstats.alerts", typeof(KlaxonInteractionStatsAlertsTopicInteractionStatAlert)},
        // {"v2.users.{0}.alerting.interactionstats.rules", typeof(KlaxonInteractionStatsRulesTopicInteractionStatRule)},
        // {"v2.users.{0}.alerting.rules", typeof(V2MobiusRulesTopicRule)},
        // {"v2.users.{0}.analytics.reporting.exports", typeof(ReportingDataExportTopicDataExportNotification)},
        // {"v2.users.{0}.badges.chats", typeof(ChatBadgeTopicChatBadge)},
        // {"v2.users.{0}.callforwarding", typeof(CallForwardingEventCallForwarding)},
        {"v2.users.{0}.conversations", typeof(ConversationEventTopicConversation)},
        // {"v2.users.{0}.conversations.callbacks", typeof(ConversationCallbackEventTopicCallbackConversation)},
        {"v2.users.{0}.conversations.calls", typeof(ConversationCallEventTopicCallConversation)},
        // {"v2.users.{0}.conversations.chats", typeof(ConversationChatEventTopicChatConversation)},
        // {"v2.users.{0}.conversations.cobrowseSessions", typeof(ConversationCobrowseEventTopicCobrowseConversation)},
        // {"v2.users.{0}.conversations.emails", typeof(ConversationEmailEventTopicEmailConversation)},
        // {"v2.users.{0}.conversations.inbound.typing.event", typeof(V2ConversationMessageTypingEventForUserTopicMessageData)},
        // {"v2.users.{0}.conversations.messages", typeof(ConversationMessageEventTopicMessageConversation)},
        // {"v2.users.{0}.conversations.screenshares", typeof(ConversationScreenShareEventTopicScreenShareConversation)},
        // {"v2.users.{0}.conversations.socialexpressions", typeof(ConversationSocialExpressionEventTopicSocialConversation)},
        // {"v2.users.{0}.conversations.summaries", typeof(ConversationSummaryTopicConversationSummaryEvent)},
        // {"v2.users.{0}.conversations.videos", typeof(ConversationVideoEventTopicVideoConversation)},
        // {"v2.users.{0}.conversations.{1}.recordings", typeof(RecordingEventRecording)},
        // {"v2.users.{0}.conversations.{1}.recordings.{2}", typeof(RecordingTranscodeCompleteTopicRecording)},
        // {"v2.users.{0}.conversationsummary", typeof(UserConversationsEventUserConversationSummary)},
        // {"v2.users.{0}.employeeengagement.celebrations", typeof(V2WemEngagementCelebrationUpdatesTopicEngagementCelebration)},
        // {"v2.users.{0}.fax.documents", typeof(FaxTopicFaxDataV2)},
        // {"v2.users.{0}.geolocation", typeof(GeolocationEventGeolocation)},
        // {"v2.users.{0}.greetings", typeof(UserGreetingEventGreeting)},
        // {"v2.users.{0}.integrationpresence", typeof(V2IntegrationPresenceEventPresenceActivityEvent)},
        // {"v2.users.{0}.outbound.contactlists.{0}.export", typeof(ContactlistDownloadReadyExportUri)},
        // {"v2.users.{0}.outbound.dnclists.{0}.export", typeof(DnclistDownloadReadyExportUri)},
        // {"v2.users.{0}.outofoffice", typeof(OutOfOfficeEventOutOfOffice)},
        // {"v2.users.{0}.persistentconnection", typeof(PersistentConnectionChangeTopicPersistentConnectionChangeEvent)},
        {"v2.users.{0}.presence", typeof(PresenceEventUserPresence)},
        // {"v2.users.{0}.recordings", typeof(RecordingArchiveRestoreTopicRecording)},
        // {"v2.users.{0}.routingStatus", typeof(UserRoutingStatusUserRoutingStatus)},
        {"v2.users.{0}.station", typeof(UserStationChangeTopicUserStations)},
        // {"v2.users.{0}.tokens", typeof(UserTokensTopicTokenNotification)},
        // {"v2.users.{0}.userrecordings", typeof(AdhocRecordingTopicRecordingDataV2)},
        // {"v2.users.{0}.voicemail.messages", typeof(VoicemailMessagesTopicVoicemailMessage)},
        // {"v2.users.{0}.wem.coaching.notification", typeof(WemCoachingUserNotificationTopicCoachingUserNotification)},
        // {"v2.users.{0}.wem.learning.assignment", typeof(LearningAssignmentTopicLearningAssignmentNotification)},
        // {"v2.users.{0}.workforcemanagement.adherence", typeof(WfmUserScheduleAdherenceUpdatedTopicUserScheduleAdherenceUpdate)},
        // {"v2.users.{0}.workforcemanagement.adherence.explanations.jobs", typeof(WfmAdherenceExplanationJobCompleteTopicAdherenceExplanationJobNotification)},
        // {"v2.users.{0}.workforcemanagement.adherence.historical.bulk", typeof(WfmHistoricalAdherenceBulkCalculationsCompleteTopicWfmHistoricalAdherenceBulkCalculationsCompleteNotification)},
        // {"v2.users.{0}.workforcemanagement.alternative.shift.jobs", typeof(WfmAlternativeShiftJobCompleteEventV3AlternativeShiftJobCompleteNotification)},
        // {"v2.users.{0}.workforcemanagement.historicaladherencequery", typeof(WfmHistoricalAdherenceCalculationsCompleteTopicWfmHistoricalAdherenceCalculationsCompleteNotice)},
        // {"v2.users.{0}.workforcemanagement.integrations.hris.timeofftypes.jobs", typeof(WfmIntegrationsHrisTimeOffTypesJobTopicHrisTimeOffTypesJobNotification)},
        // {"v2.users.{0}.workforcemanagement.notifications", typeof(WfmUserNotificationTopicWfmUserNotification)},
        // {"v2.users.{0}.workforcemanagement.performanceprediction.schedules.recalculations", typeof(PerformancePredictionRecalculationCompleteEventTopicPerformancePredictionUserRecalculationNotification)},
        // {"v2.users.{0}.workforcemanagement.schedules", typeof(WfmAgentScheduleUpdateTopicAgentScheduleUpdateNotification)},
        // {"v2.users.{0}.workforcemanagement.shrinkage.jobs", typeof(WfmHistoricalShrinkageCalculationsCompleteTopicHistoricalShrinkageCalculationsCompleteNotification)},
        // {"v2.users.{0}.workforcemanagement.timeoffbalance.jobs", typeof(WfmTimeOffBalanceJobTopicTimeOffBalanceJobNotification)},
        // {"v2.users.{0}.workforcemanagement.timeoffrequests", typeof(WfmTimeOffRequestUpdateTopicTimeOffRequestUpdate)},
        // {"v2.video.conferences.{0}", typeof(VideoConferenceUpdateTopicVideoConference)},
        // {"v2.webdeployments.configurations.{0}", typeof(WebDeploymentsConfigTopicWebMessagingConfigChangeEventBody)},
        // {"v2.webdeployments.deployments.{0}", typeof(WebDeploymentsDeploymentTopicWebMessagingDeploymentChangeEventBody)},
        // {"v2.webmessaging.deployments.{0}.undelivered.messages", typeof(V2WebMessagingUndeliveredMessageTopicWebMessagingUndeliveredMessageEventBody)},
        // {"v2.wem.learning.assignments.modules.{0}", typeof(LearningAssignmentRuleRunTopicLearningAssignmentRuleRunNotification)},
        // {"v2.workflows.{0}.conversations.inbound.typing.event", typeof(V2ConversationMessageTypingEventForWorkflowTopicMessageData)},
        // {"v2.workforcemanagement.agents", typeof(WfmMoveAgentsCompleteTopicWfmMoveAgentsComplete)},
        // {"v2.workforcemanagement.agents.{0}.adherence.explanations", typeof(WfmAgentAdherenceExplanationChangedAgentTopicAdherenceExplanationChangedNotification)},
        // {"v2.workforcemanagement.businessunits.{0}.activityplans.jobs", typeof(WfmActivityPlanJobCompleteTopicActivityPlanOccurrenceDeletionJobCompleteNotification)},
        // {"v2.workforcemanagement.businessunits.{0}.activityplans.runs.jobs", typeof(WfmActivityPlanRunJobCompleteTopicActivityPlanRunJobCompleteNotification)},
        // {"v2.workforcemanagement.businessunits.{0}.adherence.explanations", typeof(WfmAgentAdherenceExplanationChangedBusinessUnitTopicAdherenceExplanationChangedNotification)},
        // {"v2.workforcemanagement.businessunits.{0}.forecasts.staffingrequirement", typeof(WfmBuShortTermForecastStaffingRequirementsGenerateCompleteTopicBuForecastShortTermStaffingRequirementsNotification)},
        // {"v2.workforcemanagement.businessunits.{0}.schedules", typeof(WfmBuScheduleTopicBuScheduleNotification)},
        // {"v2.workforcemanagement.businessunits.{0}.scheduling.runs", typeof(WfmBuScheduleRunTopicBuSchedulingRunProgressNotification)},
        // {"v2.workforcemanagement.businessunits.{0}.shorttermforecasts", typeof(WfmBuShortTermForecastUpdateCompleteTopicBuShortTermForecastNotification)},
        // {"v2.workforcemanagement.businessunits.{0}.shorttermforecasts.copy", typeof(WfmBuShortTermForecastCopyCompleteTopicBuShortTermForecastNotification)},
        // {"v2.workforcemanagement.businessunits.{0}.shorttermforecasts.generate", typeof(WfmBuShortTermForecastGenerateProgressTopicGenerateBuShortTermForecastProgressNotification)},
        // {"v2.workforcemanagement.businessunits.{0}.shorttermforecasts.import", typeof(WfmBuShortTermForecastImportCompleteTopicBuShortTermForecastNotification)},
        // {"v2.workforcemanagement.businessunits.{0}.workplanbids.{1}", typeof(WorkPlanBiddingAdminNotificationTopicWorkPlanBiddingNotification)},
        // {"v2.workforcemanagement.historicaldata.delete.jobs", typeof(WfmHistoricalDataImportPurgeCompleteTopicHistoricalDataPurgeRequestComplete)},
        // {"v2.workforcemanagement.historicaldata.deletejob", typeof(WfmHistoricalDataUploadPurgeRequestStatusTopicHistoricalDataUploadPurgeRequestUpdate)},
        // {"v2.workforcemanagement.historicaldata.status", typeof(WfmHistoricalDataUploadRequestStatusTopicHistoricalDataUploadRequestUpdate)},
        // {"v2.workforcemanagement.managementunits.{0}", typeof(WfmMoveManagementUnitTopicMoveManagementUnitNotification)},
        // {"v2.workforcemanagement.managementunits.{0}.adherence", typeof(WfmUserScheduleAdherenceUpdatedMuTopicUserScheduleAdherenceUpdate)},
        // {"v2.workforcemanagement.managementunits.{0}.agents.sync", typeof(WfmUpdateAgentDetailsTopicWfmUpdateAgentDetailsComplete)},
        // {"v2.workforcemanagement.managementunits.{0}.schedules", typeof(WfmScheduleTopicWfmScheduleNotification)},
        // {"v2.workforcemanagement.managementunits.{0}.shifttrades.state.bulk", typeof(WfmBulkShiftTradeStateUpdateNotificationTopicBulkShiftTradeStateUpdateNotification)},
        // {"v2.workforcemanagement.performanceprediction.schedules.{0}", typeof(PerformancePredictionCompleteEventTopicPerformancePredictionCalculationNotification)},
        // {"v2.workforcemanagement.teams.{0}.adherence", typeof(WfmUserScheduleAdherenceUpdatedTeamTopicUserScheduleAdherenceUpdate)},
        // {"v2.workforcemanagement.users.{0}.schedules.query", typeof(WfmBuScheduleQueryResultTopicBuScheduleSearchResultNotification)},
        // {"v2.workforcemanagement.users.{0}.schedules.search", typeof(WfmBuScheduleSearchResultTopicBuScheduleSearchResultNotification)},
    };
}
