using System.Runtime.Serialization;
using System.Text;
using System.Text.Json.Serialization;

namespace PureCloud.Client.Models;

/// <summary>
/// Device
/// </summary>
[DataContract]
public partial class Device : IEquatable<Device>
{
    /// <summary>
    /// Device category.
    /// </summary>
    /// <value>Device category.</value>
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum CategoryEnum
    {
        /// <summary>
        /// Your SDK version is out of date and an unknown enum value was encountered. 
        /// Please upgrade the SDK using the command "Upgrade-Package PureCloudApiSdk" 
        /// in the Package Manager Console
        /// </summary>
        [EnumMember(Value = "OUTDATED_SDK_VERSION")]
        OutdatedSdkVersion,

        /// <summary>
        /// Enum Desktop for "desktop"
        /// </summary>
        [EnumMember(Value = "desktop")]
        Desktop,

        /// <summary>
        /// Enum Mobile for "mobile"
        /// </summary>
        [EnumMember(Value = "mobile")]
        Mobile,

        /// <summary>
        /// Enum Tablet for "tablet"
        /// </summary>
        [EnumMember(Value = "tablet")]
        Tablet,

        /// <summary>
        /// Enum Other for "other"
        /// </summary>
        [EnumMember(Value = "other")]
        Other
    }
    /// <summary>
    /// Device category.
    /// </summary>
    /// <value>Device category.</value>
    [DataMember(Name = "category", EmitDefaultValue = false)]
    public CategoryEnum? Category { get; set; }

    /// <summary>
    /// Initializes a new instance of the <see cref="Device" /> class.
    /// </summary>
    [JsonConstructorAttribute]
    protected Device() { }
    /// <summary>
    /// Initializes a new instance of the <see cref="Device" /> class.
    /// </summary>
    /// <param name="Category">Device category. (required).</param>
    /// <param name="Type">Device type (e.g. iPad, iPhone, Other). (required).</param>
    /// <param name="IsMobile">Flag that is true for mobile devices. (required).</param>
    /// <param name="ScreenHeight">Device&#39;s screen height..</param>
    /// <param name="ScreenWidth">Device&#39;s screen width..</param>
    /// <param name="ScreenDensity">Device&#39;s screen density, measured as a scale factor where a value of 1 represents a baseline 1:1 ratio of pixels to logical (device-independent) pixels..</param>
    /// <param name="Fingerprint">Fingerprint generated by looking at the individual device features..</param>
    /// <param name="OsFamily">Operating system family. (required).</param>
    /// <param name="OsVersion">Operating system version. (required).</param>
    /// <param name="Manufacturer">Manufacturer of the device..</param>
    public Device(CategoryEnum? Category = null, string Type = null, bool? IsMobile = null, int? ScreenHeight = null, int? ScreenWidth = null, int? ScreenDensity = null, string Fingerprint = null, string OsFamily = null, string OsVersion = null, string Manufacturer = null)
    {
        this.Category = Category;
        this.Type = Type;
        this.IsMobile = IsMobile;
        this.ScreenHeight = ScreenHeight;
        this.ScreenWidth = ScreenWidth;
        this.ScreenDensity = ScreenDensity;
        this.Fingerprint = Fingerprint;
        this.OsFamily = OsFamily;
        this.OsVersion = OsVersion;
        this.Manufacturer = Manufacturer;

    }





    /// <summary>
    /// Device type (e.g. iPad, iPhone, Other).
    /// </summary>
    /// <value>Device type (e.g. iPad, iPhone, Other).</value>
    [DataMember(Name = "type", EmitDefaultValue = false)]
    public string Type { get; set; }



    /// <summary>
    /// Flag that is true for mobile devices.
    /// </summary>
    /// <value>Flag that is true for mobile devices.</value>
    [DataMember(Name = "isMobile", EmitDefaultValue = false)]
    public bool? IsMobile { get; set; }



    /// <summary>
    /// Device&#39;s screen height.
    /// </summary>
    /// <value>Device&#39;s screen height.</value>
    [DataMember(Name = "screenHeight", EmitDefaultValue = false)]
    public int? ScreenHeight { get; set; }



    /// <summary>
    /// Device&#39;s screen width.
    /// </summary>
    /// <value>Device&#39;s screen width.</value>
    [DataMember(Name = "screenWidth", EmitDefaultValue = false)]
    public int? ScreenWidth { get; set; }



    /// <summary>
    /// Device&#39;s screen density, measured as a scale factor where a value of 1 represents a baseline 1:1 ratio of pixels to logical (device-independent) pixels.
    /// </summary>
    /// <value>Device&#39;s screen density, measured as a scale factor where a value of 1 represents a baseline 1:1 ratio of pixels to logical (device-independent) pixels.</value>
    [DataMember(Name = "screenDensity", EmitDefaultValue = false)]
    public int? ScreenDensity { get; set; }



    /// <summary>
    /// Fingerprint generated by looking at the individual device features.
    /// </summary>
    /// <value>Fingerprint generated by looking at the individual device features.</value>
    [DataMember(Name = "fingerprint", EmitDefaultValue = false)]
    public string Fingerprint { get; set; }



    /// <summary>
    /// Operating system family.
    /// </summary>
    /// <value>Operating system family.</value>
    [DataMember(Name = "osFamily", EmitDefaultValue = false)]
    public string OsFamily { get; set; }



    /// <summary>
    /// Operating system version.
    /// </summary>
    /// <value>Operating system version.</value>
    [DataMember(Name = "osVersion", EmitDefaultValue = false)]
    public string OsVersion { get; set; }



    /// <summary>
    /// Manufacturer of the device.
    /// </summary>
    /// <value>Manufacturer of the device.</value>
    [DataMember(Name = "manufacturer", EmitDefaultValue = false)]
    public string Manufacturer { get; set; }


    /// <summary>
    /// Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()
    {
        var sb = new StringBuilder();
        sb.Append("class Device {\n");

        sb.Append("  Category: ").Append(Category).Append("\n");
        sb.Append("  Type: ").Append(Type).Append("\n");
        sb.Append("  IsMobile: ").Append(IsMobile).Append("\n");
        sb.Append("  ScreenHeight: ").Append(ScreenHeight).Append("\n");
        sb.Append("  ScreenWidth: ").Append(ScreenWidth).Append("\n");
        sb.Append("  ScreenDensity: ").Append(ScreenDensity).Append("\n");
        sb.Append("  Fingerprint: ").Append(Fingerprint).Append("\n");
        sb.Append("  OsFamily: ").Append(OsFamily).Append("\n");
        sb.Append("  OsVersion: ").Append(OsVersion).Append("\n");
        sb.Append("  Manufacturer: ").Append(Manufacturer).Append("\n");
        sb.Append("}\n");
        return sb.ToString();
    }


    /// <summary>
    /// Returns true if objects are equal
    /// </summary>
    /// <param name="obj">Object to be compared</param>
    /// <returns>Boolean</returns>
    public override bool Equals(object obj)
    {
        // credit: http://stackoverflow.com/a/10454552/677735
        return Equals(obj as Device);
    }

    /// <summary>
    /// Returns true if Device instances are equal
    /// </summary>
    /// <param name="other">Instance of Device to be compared</param>
    /// <returns>Boolean</returns>
    public bool Equals(Device other)
    {
        // credit: http://stackoverflow.com/a/10454552/677735
        if (other == null)
        {
            return false;
        }

        return true &&
            (
                Category == other.Category ||
                Category != null &&
                Category.Equals(other.Category)
            ) &&
            (
                Type == other.Type ||
                Type != null &&
                Type.Equals(other.Type)
            ) &&
            (
                IsMobile == other.IsMobile ||
                IsMobile != null &&
                IsMobile.Equals(other.IsMobile)
            ) &&
            (
                ScreenHeight == other.ScreenHeight ||
                ScreenHeight != null &&
                ScreenHeight.Equals(other.ScreenHeight)
            ) &&
            (
                ScreenWidth == other.ScreenWidth ||
                ScreenWidth != null &&
                ScreenWidth.Equals(other.ScreenWidth)
            ) &&
            (
                ScreenDensity == other.ScreenDensity ||
                ScreenDensity != null &&
                ScreenDensity.Equals(other.ScreenDensity)
            ) &&
            (
                Fingerprint == other.Fingerprint ||
                Fingerprint != null &&
                Fingerprint.Equals(other.Fingerprint)
            ) &&
            (
                OsFamily == other.OsFamily ||
                OsFamily != null &&
                OsFamily.Equals(other.OsFamily)
            ) &&
            (
                OsVersion == other.OsVersion ||
                OsVersion != null &&
                OsVersion.Equals(other.OsVersion)
            ) &&
            (
                Manufacturer == other.Manufacturer ||
                Manufacturer != null &&
                Manufacturer.Equals(other.Manufacturer)
            );
    }

    /// <summary>
    /// Gets the hash code
    /// </summary>
    /// <returns>Hash code</returns>
    public override int GetHashCode()
    {
        // credit: http://stackoverflow.com/a/263416/677735
        unchecked // Overflow is fine, just wrap
        {
            int hash = 41;
            // Suitable nullity checks etc, of course :)
            if (Category != null)
            {
                hash = hash * 59 + Category.GetHashCode();
            }

            if (Type != null)
            {
                hash = hash * 59 + Type.GetHashCode();
            }

            if (IsMobile != null)
            {
                hash = hash * 59 + IsMobile.GetHashCode();
            }

            if (ScreenHeight != null)
            {
                hash = hash * 59 + ScreenHeight.GetHashCode();
            }

            if (ScreenWidth != null)
            {
                hash = hash * 59 + ScreenWidth.GetHashCode();
            }

            if (ScreenDensity != null)
            {
                hash = hash * 59 + ScreenDensity.GetHashCode();
            }

            if (Fingerprint != null)
            {
                hash = hash * 59 + Fingerprint.GetHashCode();
            }

            if (OsFamily != null)
            {
                hash = hash * 59 + OsFamily.GetHashCode();
            }

            if (OsVersion != null)
            {
                hash = hash * 59 + OsVersion.GetHashCode();
            }

            if (Manufacturer != null)
            {
                hash = hash * 59 + Manufacturer.GetHashCode();
            }

            return hash;
        }
    }
}
