using System.Text;
using System.Text.Json.Serialization;

namespace PureCloud.Client.Models;

public sealed class ArchitectFlowOutcomeNotificationArchitectOperation
{
    /// <summary>
    /// The action being performed
    /// </summary>
    /// <value>The action being performed</value>
    public ArchitectFlowOutcomeNotificationArchitectOperationActionNameEnum? ActionName { get; set; }

    /// <summary>
    /// The action status
    /// </summary>
    /// <value>The action status</value>
    public ArchitectFlowOutcomeNotificationArchitectOperationActionStatusEnum? ActionStatus { get; set; }

    /// <summary>
    /// A unique identifier for this operation, as generated by the initiating client
    /// </summary>
    /// <value>A unique identifier for this operation, as generated by the initiating client</value>
    public string Id { get; set; }

    /// <summary>
    /// Indicates if the operation is complete
    /// </summary>
    /// <value>Indicates if the operation is complete</value>
    public bool? Complete { get; set; }

    /// <summary>
    /// Gets or Sets User
    /// </summary>
    public ArchitectFlowOutcomeNotificationUser User { get; set; }

    /// <summary>
    /// Gets or Sets Client
    /// </summary>
    public ArchitectFlowOutcomeNotificationClient Client { get; set; }

    /// <summary>
    /// The error message, if the action failed
    /// </summary>
    /// <value>The error message, if the action failed</value>
    public string ErrorMessage { get; set; }

    /// <summary>
    /// The error code, if the action failed
    /// </summary>
    /// <value>The error code, if the action failed</value>
    public string ErrorCode { get; set; }

    /// <summary>
    /// Gets or Sets ErrorMessageParams
    /// </summary>
    public ArchitectFlowOutcomeNotificationErrorMessageParams ErrorMessageParams { get; set; }

    /// <summary>
    /// The error details, if the action failed
    /// </summary>
    /// <value>The error details, if the action failed</value>
    public IEnumerable<ArchitectFlowOutcomeNotificationErrorDetail> ErrorDetails { get; set; }
}
