using System.Text;
using System.Text.Json.Serialization;

namespace PureCloud.Client.Models;

public sealed class Browser
{
    /// <summary>
    /// Browser family (e.g. Chrome, Safari, Firefox).
    /// </summary>
    /// <value>Browser family (e.g. Chrome, Safari, Firefox).</value>
    public string Family { get; set; }

    /// <summary>
    /// Browser version (e.g. 68.0.3440.84).
    /// </summary>
    /// <value>Browser version (e.g. 68.0.3440.84).</value>
    public string Version { get; set; }

    /// <summary>
    /// Language the browser is set to. Must conform to BCP 47.
    /// </summary>
    /// <value>Language the browser is set to. Must conform to BCP 47.</value>
    public string Lang { get; set; }

    /// <summary>
    /// Fingerprint generated by looking at the individual browser features.
    /// </summary>
    /// <value>Fingerprint generated by looking at the individual browser features.</value>
    public string Fingerprint { get; set; }

    /// <summary>
    /// (Deprecated, use Device.isMobile instead) Flag that is true for mobile devices.
    /// </summary>
    /// <value>(Deprecated, use Device.isMobile instead) Flag that is true for mobile devices.</value>
    public bool? IsMobile { get; set; }

    /// <summary>
    /// Browser&#39;s viewport height.
    /// </summary>
    /// <value>Browser&#39;s viewport height.</value>
    public int? ViewHeight { get; set; }

    /// <summary>
    /// Browser&#39;s viewport width.
    /// </summary>
    /// <value>Browser&#39;s viewport width.</value>
    public int? ViewWidth { get; set; }

    /// <summary>
    /// Whether Flash is installed.
    /// </summary>
    /// <value>Whether Flash is installed.</value>
    public bool? FeaturesFlash { get; set; }

    /// <summary>
    /// Whether Java is installed.
    /// </summary>
    /// <value>Whether Java is installed.</value>
    public bool? FeaturesJava { get; set; }

    /// <summary>
    /// Whether the browser recognizes PDFs.
    /// </summary>
    /// <value>Whether the browser recognizes PDFs.</value>
    public bool? FeaturesPdf { get; set; }

    /// <summary>
    /// Whether WebRTC is supported.
    /// </summary>
    /// <value>Whether WebRTC is supported.</value>
    public bool? FeaturesWebrtc { get; set; }
}
