using System.Text;
using System.Text.Json.Serialization;

namespace PureCloud.Client.Models;

public sealed class Device
{
    /// <summary>
    /// Device category.
    /// </summary>
    /// <value>Device category.</value>
    public DeviceCategoryEnum? Category { get; set; }

    /// <summary>
    /// Device type (e.g. iPad, iPhone, Other).
    /// </summary>
    /// <value>Device type (e.g. iPad, iPhone, Other).</value>
    public string Type { get; set; }

    /// <summary>
    /// Flag that is true for mobile devices.
    /// </summary>
    /// <value>Flag that is true for mobile devices.</value>
    public bool? IsMobile { get; set; }

    /// <summary>
    /// Device&#39;s screen height.
    /// </summary>
    /// <value>Device&#39;s screen height.</value>
    public int? ScreenHeight { get; set; }

    /// <summary>
    /// Device&#39;s screen width.
    /// </summary>
    /// <value>Device&#39;s screen width.</value>
    public int? ScreenWidth { get; set; }

    /// <summary>
    /// Device&#39;s screen density, measured as a scale factor where a value of 1 represents a baseline 1:1 ratio of pixels to logical (device-independent) pixels.
    /// </summary>
    /// <value>Device&#39;s screen density, measured as a scale factor where a value of 1 represents a baseline 1:1 ratio of pixels to logical (device-independent) pixels.</value>
    public int? ScreenDensity { get; set; }

    /// <summary>
    /// Fingerprint generated by looking at the individual device features.
    /// </summary>
    /// <value>Fingerprint generated by looking at the individual device features.</value>
    public string Fingerprint { get; set; }

    /// <summary>
    /// Operating system family.
    /// </summary>
    /// <value>Operating system family.</value>
    public string OsFamily { get; set; }

    /// <summary>
    /// Operating system version.
    /// </summary>
    /// <value>Operating system version.</value>
    public string OsVersion { get; set; }

    /// <summary>
    /// Manufacturer of the device.
    /// </summary>
    /// <value>Manufacturer of the device.</value>
    public string Manufacturer { get; set; }
}
