namespace PureCloud.Client.Models;

/// <summary>
/// RequestDevice
/// </summary>
public sealed class RequestDevice
{
    /// <summary>
    /// RequestDevice
    /// </summary>
    public CategoryEnum? Category { get; set; }

    /// <summary>
    /// Initializes a new instance of the <see cref="RequestDevice" /> class.
    /// </summary>
    public string? Type { get; set; }

    /// <summary>
    /// Flag that is true for mobile devices.
    /// </summary>
    public bool? IsMobile { get; set; }

    /// <summary>
    /// Device&#39;s screen height.
    /// </summary>
    public int? ScreenHeight { get; set; }

    /// <summary>
    /// Device&#39;s screen width.
    /// </summary>
    public int? ScreenWidth { get; set; }

    /// <summary>
    /// Device&#39;s screen density, measured as a scale factor where a value of 1 represents a baseline 1:1 ratio of pixels to logical (device-independent) pixels.
    /// </summary>
    public int? ScreenDensity { get; set; }

    /// <summary>
    /// Fingerprint generated by looking at the individual device features.
    /// </summary>
    public string? Fingerprint { get; set; }

    /// <summary>
    /// Operating system family.
    /// </summary>
    public string? OsFamily { get; set; }

    /// <summary>
    /// Operating system version.
    /// </summary>
    public string? OsVersion { get; set; }

    /// <summary>
    /// Manufacturer of the device.
    /// </summary>
    public string? Manufacturer { get; set; }
}
