namespace PureCloud.Client.Models;

/// <summary>
/// SpeechTextAnalyticsConversationSummary
/// </summary>
public sealed class SpeechTextAnalyticsConversationSummary
{
    /// <summary>
    /// The type of summary
    /// </summary>
    public SummaryType? SummaryType { get; set; }


    /// <summary>
    /// The media type of the associated interaction
    /// </summary>
    public MediaType? MediaType { get; set; }


    /// <summary>
    /// Language of the summary
    /// </summary>
    public string Language { get; set; }


    /// <summary>
    /// The id of the agent associated with the summary
    /// </summary>
    public string AgentId { get; set; }


    /// <summary>
    /// A summarization of the conversation transcription
    /// </summary>
    public string Summary { get; set; }


    /// <summary>
    /// Indicates whether or not the summary was generated by AI
    /// </summary>
    public bool? Generated { get; set; }


    /// <summary>
    /// Timestamp of when the summary was created. Date time is represented as an ISO-8601 string. For example: yyyy-MM-ddTHH:mm:ss[.mmm]Z
    /// </summary>
    public DateTime? DateCreated { get; set; }
}