namespace PureCloud.Client.Models;

/// <summary>
/// A web messaging message
/// </summary>
public sealed class WebMessagingMessage
{
    /// <summary>
    /// Unique ID of the message. This ID is generated by Messaging Platform. Message receipts will have the same ID as the message they reference.
    /// </summary>
    public string Id { get; set; }

    /// <summary>
    /// Channel-specific information that describes the message and the message channel/provider.
    /// </summary>
    public WebMessagingChannel Channel { get; set; }

    /// <summary>
    /// Message type.
    /// </summary>
    public WebMessagingMessageType? Type { get; set; }

    /// <summary>
    /// Message text.
    /// </summary>
    public string Text { get; set; }

    /// <summary>
    /// List of content elements.
    /// </summary>
    public IEnumerable<WebMessagingContent> Content { get; set; }

    /// <summary>
    /// Message receipt status, only used with type Receipt.
    /// </summary>
    public WebMessagingMessageStatus? Status { get; set; }

    /// <summary>
    /// List of reasons for a message receipt that indicates the message has failed. Only used with Failed status.
    /// </summary>
    public IEnumerable<Reason> Reasons { get; set; }

    /// <summary>
    /// List of event elements.
    /// </summary>
    public IEnumerable<WebMessagingEvent> Events { get; set; }

    /// <summary>
    /// The direction of the message.  Direction is always from the perspective of the Genesys Cloud platform.  An Inbound message is one sent from a guest to the Genesys Cloud Platform.  An Outbound message is one sent from the Genesys Cloud Platform to a guest.
    /// </summary>
    public WebMessagingMessageDirection? Direction { get; set; }

    /// <summary>
    /// Specifies if this message was sent by a human agent or bot. The platform may use this to apply appropriate provider policies.
    /// </summary>
    public WebMessagingMessageOriginatingEntity? OriginatingEntity { get; set; }

    /// <summary>
    /// Additional metadata about this message.
    /// </summary>
    public Dictionary<string, string> Metadata { get; set; }
}